### ISSUE TITLE
Investigate how end of support for Vue2 will impact GWELLS/WALLY

### ISSUE THREAD

**Issue by jakemorr** [bcgov-c/wally#688]
**Describe the task**
Investigate how the end of support for Vue2 front end framework will impact GWELLS/WALLY and is there anything we need to do to maintain the applications.

**Purpose**
With Vue2 becoming unsupported we need to know if it is necessary to upgrade the Front end of these 2 apps

**Acceptance Criteria**
- [x] What are the impacts of Vue2 no longer being supported
- [x] What actions would we take if we remained on the unsupported framework for a bit
- [x] How much effort would it be to move to a newer version of Vue for GWELLS/Wally

**Additional context**
- End of life is December 31, 2023
- Currently operating on at least Vue 2.6.10 - to be confirmed in OpenShift
- Last version of Vue2 is 2.7
- See also: https://v2.vuejs.org/lts/

**Comment by davidclaveau** [comment]
**What are the impacts of Vue 2 no longer being supported**
The main drawbacks would be efficiency of the application for the user, as Vue 3 is seen to be faster and (now that it's been out for a while) more efficient than Vue 2. 

Certain features of Vue 3 makes coding easier, or at least offers more flexibility. Readability of a component is also generally improved with the new syntax of Vue 3.

[From Vue’s Website](https://v2.vuejs.org/lts/#Upgrade-or-not-to-Upgrade)
> Is the app stable and working well? Does the app expect continued new feature development into the future? Is there a pain-point / bottleneck that can only be solved by upgrading? If the app is stable and isn’t experiencing major pain-point caused by Vue 2, then upgrading may not be worthwhile.
> 
> Does the app rely on 3rd party dependencies that are hard to be made Vue 3 compatible? Does the app rely heavily on changed behavior between Vue 2 and Vue 3? Can the team allocate dedicated time for upgrading? Spend some initial research time to gauge these aspects and come up with an estimation, then compare that to the expected gain from. We will not be able to provide a precise formula, but hopefully this can help with the decision process.
>
>...
>
>For some teams, the main concern lies in security, compliance, and browser compatibility.
>- You won’t receive security fixes from EOL software. For the record, Vue 2 hasn’t really had any real vulnerabilities in the past, but you may need a supported version to fullfil regulations or company policies.
>- If you are shipping your application to customers with SLAs. You will want to avoid including EOL software in your stack.
>- Browsers sometimes ship changes that break legacy libraries. This is extremely rare, but could happen in theory.

[Efficiency](https://geckodynamics.com/blog/Vue2-vs-Vue3):
> [From 2020] Users report that Vue 3 is about 55 percent faster, memory usage is down to 54 percent and updates are up to 133 percent faster. This is achieved by completely rewriting the DOM implementation using TypeScript.

---

**What actions would we take if we remained on the unsupported framework for a bit**
Most of the things we do with Vue 2 would not change day-to-day, as the framework will still be working reliably how it is.

We may see issues in the future when dependencies or libraries that Vue 2 uses now might become out of date, as those libraries focus their resources on updating for Vue 3 instead. This means that dependencies will most likely become further out of date as time goes on.

According to Vue's website, we should see some good reliability in 2.7 natively for some time:

[From Vue’s Website](https://v2.vuejs.org/lts/#Upgrade-or-not-to-Upgrade)
> From a technical perspective, Vue 2 is a stable and battle-tested piece of technology. If it is serving you well now, it will continue to do so for the foreseeable future.
> 
> In addition, we have backported some of the most important Vue 3 features to Vue 2.7, including Composition API and `<script setup>`. This allows Vue 2 projects to improve scalability, leverage new ecosystem libraries, and better prepare for potential migration to Vue 3.

---

**How much effort would it be to move to a newer version of Vue for GWELLS/Wally**
I made some preliminary changes locally to see what a Vue 3 migration on GWELLS would look like, and it looks to be quite an undertaking for each of our components due to outdated syntax that cascades into different errors.

It’s difficult to estimate the exact amount of time it would take to migrate fully from Vue 2 to Vue 3, but it might be more than a few weeks or months of work as GWELLS has more than 100 components - and then it might take a good portion of time to bug-whack anything that crops up that might not have been caught during initial testing.
